version: '3'
services:
  mariadb:
    image: mariadb:10.4.7
    container_name: mariadb
    ports:
      - 4306:3306
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./init.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: sampledb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
