version: '3'
services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    ports:
      - 6432:5432
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: sampledb
